# Generated by Django 4.2.9 on 2024-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('repos_count', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following_count', models.IntegerField()),
            ],
        ),
    ]
