# Generated by Django 4.2.9 on 2024-01-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubstats',
            old_name='followers',
            new_name='followers_count',
        ),
    ]
