# Generated by Django 4.2.9 on 2024-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats_app', '0002_rename_followers_githubstats_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubstats',
            name='repos_count',
            field=models.IntegerField(default=0),
        ),
    ]
