# Generated by Django 4.2.9 on 2024-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats_app', '0003_alter_githubstats_repos_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubstats',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubstats',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
